version: "3.3"
services:

  redis:
    image: redis:6.0-rc
    container_name: ${PROJECT_NAME}-redis
    ports:
      - 6379

  mongo:
    image: mongo:3.4-xenial
    container_name: ${PROJECT_NAME}-mongo
    restart: unless-stopped
    ports:
      - 27017
    env_file:
      - .env.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - tipi-mongo:/data/db

  tipi-engine:
    image: ${PROJECT_NAME}-engine:${BRANCH}
    container_name: ${PROJECT_NAME}-engine
    restart: unless-stopped
    env_file:
      - .env.mongo
      - .env.engine
    ports:
      - 8091:8091
    depends_on:
      - mongo

  tipi-backend:
    image: ${PROJECT_NAME}-backend:${BRANCH}
    container_name: ${PROJECT_NAME}-backend
    restart: unless-stopped
    env_file:
      - .env.mongo
      - .env.backend
    ports:
      - ${BACKEND_PORT}:5000
    depends_on:
      - mongo

  tipi-frontend:
    image: ${PROJECT_NAME}-frontend:${BRANCH}
    container_name: ${PROJECT_NAME}-frontend
    restart: unless-stopped
    env_file:
      - .env.frontend
    ports:
      - ${FRONTEND_PORT}:80
    depends_on:
      - mongo

  tipi-alerts:
    image: ${PROJECT_NAME}-alerts:${BRANCH}
    container_name: ${PROJECT_NAME}-alerts
    restart: unless-stopped
    env_file:
      - .env.mongo
      - .env.alerts
    depends_on:
      - redis
      - mongo

volumes:
  tipi-mongo:
