services:
  redis:
    image: redis:7.4
    container_name: ${PROJECT_NAME}-redis
    ports:
      - 6379

  mongo:
    image: mongo:7.0-jammy
    container_name: ${PROJECT_NAME}-mongo
    restart: unless-stopped
    ports:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: tipi
      MONGO_INITDB_ROOT_PASSWORD: tipi
      MONGO_INITDB_DATABASE: tipidb
    volumes:
      - ./mongo-init.js.example:/docker-entrypoint-initdb.d/mongo-init.js
      - tipi-vol-mongo:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: ${PROJECT_NAME}-mongo-express
    restart: unless-stopped
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: tipi
      ME_CONFIG_MONGODB_ADMINPASSWORD: tipi
      ME_CONFIG_BASICAUTH_USERNAME: tipi
      ME_CONFIG_BASICAUTH_PASSWORD: tipi

  tipi-engine:
    build:
      context: ${ENGINE_PATH}
      dockerfile: Dockerfile-dev
    container_name: ${PROJECT_NAME}-engine
    restart: unless-stopped
    env_file:
      - ${ENGINE_PATH}/.env
    volumes:
      - ${ENGINE_PATH}:/app
    depends_on:
      - mongo

  tipi-backend:
    build:
      context: ${BACKEND_PATH}
      dockerfile: Dockerfile-dev
    container_name: ${PROJECT_NAME}-backend
    restart: unless-stopped
    env_file:
      - ${BACKEND_PATH}/.env
    volumes:
      - ${BACKEND_PATH}:/app
    ports:
      - ${BACKEND_PORT}:5000
    depends_on:
      - mongo
    command: gunicorn --bind 0.0.0.0:5000 --access-logfile - tipi_backend.wsgi:app --reload

  tipi-frontend:
    build:
      context: ${FRONTEND_PATH}
      dockerfile: Dockerfile-dev
    container_name: ${PROJECT_NAME}-frontend
    restart: unless-stopped
    env_file:
      - ${FRONTEND_PATH}/.env
    volumes:
      - ${FRONTEND_PATH}:/app
      - /app/node_modules
    command: npm run dev -- --host
    ports:
      - ${FRONTEND_PORT}:5173
    depends_on:
      - tipi-backend

  tipi-tasks:
    build:
      context: ${TASKS_PATH}
      dockerfile: Dockerfile-dev
    container_name: ${PROJECT_NAME}-tasks
    restart: unless-stopped
    env_file:
      - ${TASKS_PATH}/.env
    volumes:
      - ${TASKS_PATH}:/app
    depends_on:
      - redis
      - mongo
    user: "1000:1000"

volumes:
  tipi-vol-mongo:
