version: "3.3"
services:

  redis:
    image: redis:6.0-rc
    container_name: ${PROJECT_NAME}-redis
    restart: unless-stopped
    ports:
      - 6379

  mongo:
    image: mongo:4.4-bionic
    container_name: ${PROJECT_NAME}-mongo
    restart: unless-stopped
    ports:
      - 27017
    env_file:
      - .env.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - tipi-mongo:/data/db

  tipi-engine:
    image: politicalwatch/tipi-engine:${BRANCH}
    container_name: ${PROJECT_NAME}-engine
    restart: unless-stopped
    env_file:
      - .env.mongo
      - .env.engine
    ports:
      - 8091:8091
    depends_on:
      - mongo

  tipi-backend:
    image: politicalwatch/tipi-backend:${BRANCH}
    container_name: ${PROJECT_NAME}-backend
    restart: unless-stopped
    env_file:
      - .env.mongo
      - .env.backend
    # command: if you want to add different command
    ports:
      - ${BACKEND_PORT}:5000
    depends_on:
      - mongo

  tipi-frontend:
    image: politicalwatch/${FRONTEND}:${BRANCH}
    container_name: ${PROJECT_NAME}-frontend
    restart: unless-stopped
    env_file:
      - .env.frontend
    ports:
      - ${FRONTEND_PORT}:80
    depends_on:
      - mongo
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf

  tipi-tasks:
    image: politicalwatch/tipi-tasks:${BRANCH}
    container_name: ${PROJECT_NAME}-tasks
    restart: unless-stopped
    env_file:
      - .env.mongo
      - .env.tasks
    depends_on:
      - redis
      - mongo

volumes:
  tipi-mongo:
